---@class Ball
---@field new fun(self: Ball): Ball
---@field checkCollision fun(self: Ball, e: any): boolean
---@field draw fun(self: Ball)
---@field getGeometry fun(self: Ball): DiscGeometry
---@field invert fun(self: Ball, axis: string)
---@field markAsDestroyable fun(self: Ball)
---@field move fun(self: Ball, context: { dt: number, layout: Layout })
---@field moveLeft fun(self: Ball, context: { dt: number, speed: number })
---@field moveRight fun(self: Ball, context: { dt: number,speed: number })
---@field resolveCollision fun(self: Ball, context: BallCollisionContext)
---@field resolveOutOfBound fun(self: Ball, context: { live_area: LiveArea }): boolean
---@field stickToPaddle fun(self: Ball, context: SetGluedContext)
---@field slowDown fun(self: Ball)
---@field speedUp fun(self: Ball)
---@field resetSpeed fun(self: Ball)
---@field update fun(self: Ball, dt: number)
---@field destroyable boolean
---@field diameter number
---@field dx number
---@field dy number
---@field glued boolean
---@field last LastPosition
---@field radius number
---@field speed number
---@field stateMachine StateMachine
---@field x number
---@field y number

---@class LastPosition
---@field x number
---@field y number
