---@class Brick : Rectangle
---@field new fun(self: Brick): Brick
---@field draw fun(self: Brick)
---@field markAsDestroyable fun(self: Brick)
---@field resolveBallCollision fun(self: Brick, ball: Ball)
---@field resolveLaserCollision fun(self: Brick, laser: Laser)
---@field destroyable boolean
---@field height number
---@field hits number
---@field kind BrickKind
---@field points number
---@field power_up? PowerUpName
---@field width number
---@field x number
---@field y number

---@class BricksKinds
---@field [string] BrickKind

---@class BrickKind
---@field hits number
---@field points number
---@field rgb integer[]  -- RGB color array: { r, g, b }
