---@class Game
---@field ball Ball
---@field current_player number
---@field layout Layout
---@field level Level
---@field paddle Paddle
---@field players Player[]
---@field stateMachine StateMachine
---@field walls Walls
---@field nextRound fun(self: Game)
