---@class Laser : Disc
---@field new fun(self: Laser, params: LaserConfig): Laser
---@field draw fun(self: Laser)
---@field markAsDestroyable fun(self: Laser)
---@field move fun(self: Laser, dt: number)
---@field resolveOutOfBound fun(self: Laser, context: { live_area: LiveArea }): boolean
---@field update fun(self: Laser, dt: number)
---@field destroyable boolean
---@field dx number
---@field dy number
---@field last LastPosition
