---@class Paddle : Rectangle
---@field draw fun(self: Paddle)
---@field equipLaser fun(self: Paddle)
---@field extend fun(self: Paddle)
---@field is_out fun(self: Paddle, context: Wall): boolean
---@field makeNonSticky fun(self: Paddle)
---@field makeSticky fun(self: Paddle)
---@field move_left fun(self: Paddle, context: PaddleContext)
---@field move_right fun(self: Paddle, context: PaddleContext)
---@field move_out fun(self: Paddle, context: PaddleContext)
---@field resolveCollision fun(self: Paddle, context: PaddleCollisionContext)
---@field shrink fun(self: Paddle)
---@field resetSize fun(self: Paddle)
---@field unequipLaser fun(self: Paddle)
---@field update fun(self: Paddle, dt: number, context: PaddleUpdateContext)
---@field hasLaser boolean
---@field isSticky boolean
---@field speed number
---@field last LastPosition

---@class PaddleContext
---@field dt number
---@field layout Layout
