---@class Player
---@field current_level number
---@field level Level
---@field lives Life[]
---@field name string
---@field score Score
---@field draw fun(self: Player)
---@field extraLife fun(self: Player)
---@field nextLevel fun(self: Player)
