---@class Rectangle
---@field x number
---@field y number
---@field width number
---@field height number
---@field top number
---@field right number
---@field bottom number
---@field left number
---@field getGeometry fun(self: Rectangle): RectangleGeometry
