local M = {}
M.name = "Level 2"
M.rows = {
    {},
    { { kind = "white" } },
    { { kind = "white" }, { kind = "orange" } },
    { { kind = "white" }, { kind = "orange" }, { kind = "cyan" } },
    { { kind = "white" }, { kind = "orange" }, { kind = "cyan" }, { kind = "green" } },
    { { kind = "white" }, { kind = "orange" }, { kind = "cyan" }, { kind = "green" }, { kind = "red" } },
    { { kind = "white" }, { kind = "orange" }, { kind = "cyan" }, { kind = "green" }, { kind = "red" }, { kind = "blue" } },
    { { kind = "white" }, { kind = "orange" }, { kind = "cyan" }, { kind = "green" }, { kind = "red" }, { kind = "blue" }, { kind = "purple" } },
    {
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
        { kind = "red" },
        { kind = "blue" },
        { kind = "purple" },
        { kind = "yellow" },
    },
    {
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
        { kind = "red" },
        { kind = "blue" },
        { kind = "purple" },
        { kind = "yellow" },
        { kind = "white" },
    },
    {
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
        { kind = "red" },
        { kind = "blue" },
        { kind = "purple" },
        { kind = "yellow" },
        { kind = "white" },
        { kind = "orange" },
    },
    {
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
        { kind = "red" },
        { kind = "blue" },
        { kind = "purple" },
        { kind = "yellow" },
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
    },
    {
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
        { kind = "red" },
        { kind = "blue" },
        { kind = "purple" },
        { kind = "yellow" },
        { kind = "white" },
        { kind = "orange" },
        { kind = "cyan" },
        { kind = "green" },
    },
    {
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
        { kind = "gold" },
    },
}

return M
